# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLdtk0Xkk9ktGuY4jE1BK6jUbl454-T2
"""

import json
import re

input_file = "/content/drive/MyDrive/datas/result.json"
output_file = "/content/drive/MyDrive/datas/dta.txt"
my_name = "Mans"

def clean_text(text):
    if isinstance(text, list):
        text = "".join([t['text'] if isinstance(t, dict) else t for t in text])
    return text.strip()

with open(input_file, encoding='utf-8') as f:
    data = json.load(f)

chats = data.get('chats', {}).get('list', [])
dialogs = []

print(f"Chats found: {len(chats)}")

for chat in chats:
    messages = chat.get('messages', [])

    for i in range(len(messages) - 1):
        msg_in = messages[i]
        msg_out = messages[i+1]

        if 'from' not in msg_in or 'from' not in msg_out:
            continue

        text_in = clean_text(msg_in.get('text', ''))
        text_out = clean_text(msg_out.get('text', ''))

        if not text_in or not text_out:
            continue

        if msg_in['from'] != my_name and msg_out['from'] == my_name:

            line = f"### Instruction: {text_in} ### Response: {text_out}"
            dialogs.append(line)

print(f"Dialogs collected: {len(dialogs)}")

with open(output_file, "w", encoding='utf-8') as f:
    for line in dialogs:
        f.write(line + "\n")

print(f"Saved in {output_file}.")



from google.colab import drive
drive.mount('/content/drive')